const Food = [
    {
        id: 1,
        nama: "Soto Betawi",
        desc: "Hai",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 2,
        nama: "Ketoprak",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 3,
        nama: "Sayur Besan",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 4,
        nama: "Asinan Betawi",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 5,
        nama: "Kue Geplak",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 6,
        nama: "Nasi Ulam",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 7,
        nama: "Semur Jengkol",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 8,
        nama: "Ayam Sampyok",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 9,
        nama: "Nasi Kebuli",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 10,
        nama: "Nasi Uduk Betawi",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 11,
        nama: "Soto Betawi",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 12,
        nama: "Soto Betawi",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 13,
        nama: "Soto Betawi",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 14,
        nama: "Soto Betawi",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
    {
        id: 15,
        nama: "Soto Betawi",
        desc: "",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [],
        cara: [],
    },
];

module.exports = Food;