const Food = [
    {
        id: 1,
        nama: "Soto Betawi",
        desc: "Soto Betawi adalah hidangan khas Jakarta berupa sup berkuah santan yang kaya akan rempah, disajikan dengan potongan daging sapi atau jeroan, kentang, dan tomat. Rasanya gurih dan lezat, sering dinikmati dengan tambahan emping, bawang goreng, dan perasan jeruk limau.",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [
            "500 g daging sapi has bagian sandung lamur, potong-potong",
            "200 g babat sapi, rebus, potong 2 * 2 cm", 
            "200 g paru sapi, rebus, potong 2 * 2 cm",
            "3 sdm kecap manis",
            "3 cm kayumanis",
            "1 sdt pala bubuk",
            "4 buah cengkeh utuh",
            "3 buah batang serai, memarkan",
            "5 buah daun jeruk, buang tulang, iris memanjang",
            "2 cm lengkuas, memarkan",
            "4 sdt garam",
            "2 lembar daun salam",
            "1 sdt gula pasir",
            "1/2 sdt merica bubuk",
            "500 ml santan dari 1 butir kelapa",
            "2 sdm minyak",
            "2 l air",
            "[Bumbu Halus]",
            "12 butir bawang merah",
            "6 siung bawang putih",
            "3 buah kemiri, disangrai",
            "2 cm jahe",
            "1 sdt ketumbar bubuk",
            "[Bahan Pelengkap]",
            "2 buah tomat, potong dadu 2 cm",
            "2 batang daun bawang, iris tipis",
            "100 g bawang merah goreng",
            "50 g emping goreng",
            "4 buah jeruk nipis, belah jadi 2 bagian"
        ],
        cara: [],
    },
    {
        id: 2,
        nama: "Ketoprak",
        desc: "Ketoprak adalah makanan khas Jakarta yang terdiri dari lontong, tahu goreng, bihun, dan tauge, disajikan dengan bumbu kacang yang gurih, kecap manis, dan taburan bawang goreng. Hidangan ini biasanya dilengkapi dengan kerupuk dan potongan mentimun untuk menambah kesegaran. ",
        Kategori: "Sayur, Kacang, Tahu, Lontong",
        image: "",
        bahan: [
            "2 buah tahu putih",
            "2 buah ketupat, potong",
            "50 g taoge",
            "100 g bihun",
            "3 sdm kecap manis",
            "[Bumbu Kacang]",
            "150 g kacang tanah",
            "1 sdm gula merah, sisir",
            "1 siung bawang putih",
            "4 buah cabai rawit merah",
            "1/2 sdt garam",
            "2 sdm air asam jawa",
            "air secukupnya",
            "[Bahan Pelengkap]",
            "1 sdm bawang merah goreng",
            "kerupuk kuning"
        ],
        cara: [],
    },
    {
        id: 3,
        nama: "Sayur Besan",
        desc: "Sayur Besan adalah hidangan tradisional Betawi yang biasanya disajikan pada acara pernikahan, terdiri dari terubuk (bungkil bunga tebu), ebi, kentang, dan kacang panjang yang dimasak dalam kuah santan beraroma rempah. Rasanya gurih dan sedikit manis, mencerminkan kekayaan kuliner Betawi.",
        Kategori: "Sayur, Kuah, Santan",
        image: "",
        bahan: [
            "8 batang telur terubuk/bunga tebu",
            "1 buah (200 g) kentang, kupas",
            "100 g buncis",
            "1 papan petai",
            "3 sdm minyak goreng",
            "3 lembar daun salam",
            "3 cm lengkuas, memarkan",
            "2 sdm ebi sangrai, biarkan utuh",
            "4 buah cabai merah, iris serong",
            "4 buah cabai hijau, iris serong",
            "1250 ml santan dari 1/2 butir kelapa",
            "2 batang daun bawang, iris 3 cm",
            "2 - 3 sdt garam",
            "2 sdt gula pasir",
            "10 g suun, siram air mendidih, potong 10 cm",
            "[Bumbu Halus]",
            "10 butir bawang merah",
            "3 siung bawang putih"
        ],
        cara: [],
    },
    {
        id: 4,
        nama: "Asinan Betawi",
        desc: "Asinan Betawi adalah hidangan segar berupa campuran potongan buah-buahan seperti nanas, mangga muda, timun, dan kacang panjang yang direndam dalam larutan air asam yang manis pedas, biasanya disajikan dengan tambahan kerupuk dan bawang goreng sebagai pelengkap.",
        Kategori: "Kuah, Santan",
        image: "",
        bahan: [
            "250 g tahu putih, kukus, potong dadu",
            "125 g mi kuning, rebus, tiriskan",
            "125 g mentimun, potong dadu",
            "125 g kol, iris tipis",
            "125 g daun selada",
            "100 g sawi asin",
            "75 g lokio",
            "75 g kacang tanah goreng tanpa kulit",
            "[Bumbu Halus]",
            "150 g kacang tanah goreng dengan kulit",
            "3 buah cabai rawit merah",
            "1 buah cabai merah besar",
            "1.5 sdt cuka",
            "1 sdt air jeruk nipis",
            "3 sdm gula pasir",
            "2 sdt Royco kaldu ayam",
            "[Bahan Saus]",
            "500 ml air",
            "3 sdm gula merah",
            "4 sdm kecap manis",
            "[Pelengkap]",
            "Bawang goreng",
            "Kerupuk mi",
            "Kerupuk merah"
        ],
        cara: [],
    },
    {
        id: 5,
        nama: "Kue Geplak",
        desc: "Kue Geplak adalah jajanan tradisional Jawa Tengah yang terbuat dari campuran kelapa parut, gula merah, dan tepung ketan yang kemudian dipadatkan dan dibentuk bulat pipih. Rasanya manis gurih dengan tekstur yang kenyal, sering menjadi pilihan camilan yang lezat di Indonesia.",
        Kategori: "Kue, Kelapa",
        image: "",
        bahan: [
             "1 kg tepung beras giling (atau tepung kemasan)",
             "1 butir kelapa parut",
             "300 g gula merah",
             "200 g gula pasir",
             "1 sdt garam",
             "600 ml air",
             "10 lembar daun pandan",
             "[Taburan] 100 g tepung beras sangrai]",
            ],
        cara: [],
    },
    {
        id: 6,
        nama: "Nasi Ulam",
        desc: " Nasi Ulam adalah hidangan nasi yang dicampur dengan rempah-rempah, daun-daunan segar seperti daun kemangi, daun jeruk purut, dan daun serai, serta bumbu-bumbu lainnya seperti serai, lengkuas, dan bawang merah yang diuleg hingga harum. Biasanya disajikan dengan lauk seperti ayam goreng, ikan bakar, atau tempe goreng.",
        Kategori: "Nasi, Kelapa, Bihun",
        image: "",
        bahan: [
            "[Nasi]",
            "2 gelas beras",
            "2 gelas air",
            "1 cm serai, memarkan",
            "1/4 sdt garam",
            "1 sdm minyak",
            "[Serundeng]",
            "200 g kelapa, parut memanjang",
            "100 g gula merah, sisir halus",
            "2 lembar daun salam",
            "3 cm lengkuas, memarkan",
            "50 ml air",
            "[Bumbu Halus untuk Serundeng]",
            "1 sdm ketumbar, sangrai",
            "2 siung bawang putih",
            "3 siung bawang merah",
            "1/2 sdt garam",
            "[Semur]",
            "5 potong tahu putih",
            "1/2 cm kayu manis",
            "Secuil kecil buah pala",
            "3 sdm kecap manis",
            "100 ml air",
            "[Bumbu Halus untuk Semur]",
            "2 siung bawang putih",
            "3 siung bawang merah",
            "2 butir kemiri",
            "1/4 sdt garam",
            "1/4 sdt merica",
            "[Bihun Goreng]",
            "1/2 bungkus bihun, rendam air panas lalu tiriskan",
            "1 buah wortel, potong bulat",
            "6 lembar daun kol, sobek kasar",
            "2 sdm kecap manis",
            "[Bumbu Halus untuk Bihun Goreng]",
            "2 siung bawang putih",
            "1 butir kemiri",
            "1/4 sdt garam",
            "1/4 sdt merica",
            "[Telur Dadar]",
            "2 butir telur ayam, kocok lepas",
            "1/4 sdt garam",
            "1/4 sdt merica"
        ],
        cara: [],
    },
    {
        id: 7,
        nama: "Semur Jengkol",
        desc: "Semur Jengkol adalah hidangan khas Betawi yang terbuat dari jengkol yang dimasak dengan bumbu rempah seperti bawang merah, bawang putih, ketumbar, dan lengkuas, serta tambahan gula merah, kecap manis, dan santan untuk menciptakan kuah kental beraroma. Rasanya gurih manis dengan aroma rempah yang khas, sering disajikan sebagai lauk pendamping nasi.",
        Kategori: "Semur, Jengkol, Pedas",
        image: "",
        bahan: [
            "300 g jengkol tua",
            "6 butir bawang merah, iris tipis",
            "2 lembar daun salam",
            "5 sdm kecap manis",
            "1 sdm gula merah, sisir",
            "1 gelas air",
            "garam secukupnya",
            "[Bumbu Halus]",
            "3 siung bawang putih",
            "2 butir kemiri",
            "10 cabe merah keriting",
            "5 cabe rawit",
            "1/2 sdm ketumbar",
            "1/2 sdt merica butiran",
            "1/4 buah pala",
            "Sejumput jinten"
        ],
        cara: [],
    },
    {
        id: 8,
        nama: "Ayam Sampyok",
        desc: "Ayam Sampyok adalah hidangan khas Betawi yang terdiri dari potongan ayam yang dimarinasi dengan bumbu rempah seperti bawang merah, bawang putih, jahe, kunyit, dan kemiri, lalu dipanggang atau dibakar hingga matang dengan aroma harum yang khas. Biasanya disajikan dengan sambal dan lalapan sebagai pelengkap.",
        Kategori: "Ayam, Kacang, Santan",
        image: "",
        bahan: [
            "1 ekor ayam, belah bagian dada, lebarkan",
            "[Bahan Marinasi]",
            "Lemon/Jeruk nipis",
            "1/2 sdt garam",
            "[Bumbu Iris]",
            "3 batang serai, ambil bagian putih",
            "3 siung bawang putih",
            "3 butir bawang merah",
            "[Bumbu Halus]",
            "15 buah cabai keriting merah",
            "10 buah rawit oranye",
            "5 butir kemiri sangrai",
            "7 siung bawang putih",
            "7 butir bawang merah",
            "1 jari kunyit",
            "1 ruas jahe",
            "1 sdt lada",
            "1 sdm ketumbar",
            "100 g kacang tanah goreng",
            "[Bumbu Cemplung]",
            "3 lembar daun salam",
            "5 lembar daun jeruk, sobek-sobek",
            "5 ruas jari lengkuas, memarkan",
            "1,5 sdt garam",
            "1 sdt kaldu jamur",
            "2 ibu jari gula merah",
            "500 ml santan",
            "[Pelengkap]",
            "Sambal dan lalap"
        ],
        cara: [],
    },
    {
        id: 9,
        nama: "Nasi Kebuli",
        desc: "Nasi Kebuli adalah hidangan nasi yang berasal dari Timur Tengah namun populer di Indonesia, terdiri dari nasi yang dimasak dengan rempah-rempah seperti kayu manis, cengkeh, dan kapulaga, kemudian ditambahkan dengan potongan daging kambing atau domba yang diolah dengan bumbu khusus dan kacang-kacangan. Rasanya gurih, harum rempah, dan dagingnya lembut, sering disajikan dalam acara-acara spesial.",
        Kategori: "Nasi, Daging, Sapi",
        image: "",
        bahan: [
            "400 g daging sapi has dalam potong dadu",
            "800 g beras bulir panjang",
            "100 g bawang bombay",
            "5 cm kayu manis",
            "1/2 sdt pala bubuk",
            "2 g cengkeh",
            "4 buah kapulaga",
            "4 sdm margarin",
            "1 sdt garam",
            "1 sdt Royco kaldu sapi",
            "3 sdm kismis",
            "[Bumbu Halus]",
            "10 buah bawang merah",
            "4 siung bawang putih",
            "4 cm jahe",
            "1/2 sdm ketumbar disangrai",
            "1/2 sdt merica putih butir disangrai",
            "1/2 sdt jintan",
            "[Pelengkap]",
            "3 sdm bawang merah goreng",
            "Acar nanas"
        ],
        cara: [],
    },
    {
        id: 10,
        nama: "Nasi Uduk Betawi",
        desc: "Nasi Uduk adalah hidangan khas Betawi yang terdiri dari nasi yang dimasak dengan santan, serai, daun salam, dan daun jeruk, memberikan aroma harum yang khas. Biasanya disajikan dengan pelengkap seperti ayam goreng, telur, tempe goreng, sambal, dan krupuk, menjadi hidangan sarapan atau makanan sehari-hari yang populer di Jakarta.",
        Kategori: "Nasi, Kentang, Tempe, Semur",
        image: "",
        bahan: [
            "[Nasi]",
            "400 g beras",
            "600 ml santan",
            "3 lembar daun salam",
            "1 batang serai, geprek",
            "2 cm jahe, geprek",
            "2 cm lengkuas, geprek",
            "Garam secukupnya",
            "[Sambal Kacang]",
            "2 buah cabe merah besar, goreng",
            "3 buah cabe rawit, goreng",
            "2 siung bawang putih, goreng",
            "150 g kacang tanah, goreng",
            "1/4 sdt cuka",
            "1 sdt gula",
            "1/2 sdt garam",
            "100 ml air panas",
            "[Perkedel Kentang]",
            "500 g kentang, potong-potong kemudian goreng sampai matang dan haluskan",
            "1 batang daun bawang, iris halus",
            "4 siung bawang merah, goreng",
            "2 siung bawang putih, goreng",
            "3/4 sdt garam",
            "1/2 sdt merica bubuk",
            "1 butir telur, kocok lepas",
            "Minyak untuk menggoreng secukupnya",
            "[Semur Tahu & Telur]",
            "4 buah tahu, potong masing-masing menjadi 2 bagian dan goreng hingga matang",
            "4 butir telur ayam, rebus",
            "5 sdm minyak untuk menumis",
            "150 ml air",
            "1/2 buah tomat, potong-potong",
            "1 batang serai, geprek",
            "[Bumbu Halus]",
            "3 siung bawang merah",
            "3 siung bawang putih",
            "1/4 sdt merica",
            "3 butir kemiri, sangrai",
            "1/2 sdt garam",
            "1/2 sdt gula",
            "[Orek Tempe]",
            "250 g tempe, iris tipis kotak",
            "4 siung bawang merah, iris tipis",
            "4 siung bawang putih, iris tipis",
            "3 buah cabe merah besar, iris serong",
            "1 ruas lengkuas, geprek",
            "2 batang sereh, geprek",
            "2 lembar daun salam",
            "1 sdm gula merah, sisir halus",
            "3 sdm gula pasir",
            "3 sdm air asam jawa",
            "1 sdt garam",
            "50 ml air",
            "Minyak untuk menggoreng secukupnya"
        ],
        cara: [],
    },    
    {
        id: 11,
        nama: "Laksa Betawi",
        desc: "Laksa Betawi adalah hidangan khas Betawi yang terdiri dari mie tebal yang disajikan dalam kuah santan beraroma rempah seperti kunyit, ketumbar, dan lengkuas, ditambahkan dengan potongan daging sapi, telur rebus, tauge, kacang panjang, dan kadang-kadang jeroan. Rasanya kaya dan gurih dengan sentuhan pedas dan segar, sering dihidangkan dengan perasan jeruk nipis dan emping sebagai tambahan.",
        Kategori: "Kuah, Kaldu, Ayam",
        image: "",
        bahan: [
            "1/2 ekor ayam kampung",
            "1200 ml air, untuk merebus",
            "250 g udang kupas",
            "2 batang serai, memarkan",
            "2 lembar daun jeruk",
            "1 sdt Royco Kaldu Ayam",
            "200 ml susu rendah lemak",
            "2 sdm minyak, untuk menumis",
            "[Bumbu Halus]",
            "8 butir bawang merah",
            "4 siung bawang putih",
            "4 butir kemiri, sangrai",
            "4 cm kunyit",
            "1 sdt ketumbar butiran",
            "1/4 sdt jintan bubuk",
            "1 sdm ebi",
            "1 sdt garam",
            "[Pelengkap]",
            "200 g bihun kering, seduh air panas, tiriskan",
            "100 g taoge, seduh air panas, tiriskan",
            "4 butir telur rebus, belah 2",
            "Daun kemangi",
            "Bawang goreng",
            "Sambal rawit",
            "Jeruk limau",
            "Kecap manis"
        ],
        cara: [],
    },
    {
        id: 12,
        nama: "Kerak Telor",
        desc: "Kerak Telor adalah makanan khas Betawi berupa adonan tepung beras yang digoreng dengan telur ayam dan bumbu-bumbu seperti ebi, bawang merah, dan kelapa parut, kemudian disajikan dengan taburan bawang goreng dan serundeng. Rasanya gurih dengan aroma harum yang khas, sering dijumpai di festival atau acara khusus di Jakarta seperti Pekan Raya Jakarta (PRJ).",
        Kategori: "Telur, Telor",
        image: "",
        bahan: [
            "100 g beras ketan, bersihkan dan rendam dalam air selama 2 jam",
            "5 butir telur bebek",
            "5 sdm bubuk ebi",
            "5 sdm garam",
            "5 sdm bawang goreng",
            "5 sdm serundeng",
            "2,5 sdm gula",
            "5 butir cabai",
            "2,5 sdt bubuk merica"
        ],
        cara: [],
    },
    {
        id: 13,
        nama: "Gabus Pucung",
        desc: "Gabus Pucung adalah hidangan khas Betawi yang terdiri dari ikan gabus yang digoreng dan disajikan dengan bumbu pedas manis yang terbuat dari cabai, bawang merah, bawang putih, dan gula merah yang dimasak hingga mengental. Rasanya pedas, manis, dan gurih dengan tekstur ikan yang lembut, sering menjadi hidangan favorit di warung makan Betawi.",
        Kategori: "Ikan, Santan, Pedas",
        image: "",
        bahan: [
            "1 ekor ikan gabus",
            "2 sdm air jeruk nipis",
            "1 sdt garam",
            "750 ml air",
            "3 sdm kecap manis",
            "1 sdm bawang merah goreng",
            "300 ml minyak sayur",
            "[Marinasi Ikan, haluskan]",
            "4 siung bawang putih",
            "3 sdt ketumbar butiran, sangrai",
            "2 buah jeruk nipis, peras",
            "1/2 sdt garam",
            "[Bumbu Halus]",
            "12 butir bawang merah",
            "8 siung bawang putih",
            "6 buah cabai merah keriting",
            "3 cm kunyit",
            "6 buah kluwek, ambil isinya",
            "4 butir kemiri, sangrai",
            "[Pelengkap Ikan Gabus]",
            "1 buah jeruk limau",
            "1 batang daun bawang, iris serong",
            "7 buah cabai rawit merah",
            "4 buah serai, memarkan",
            "3 cm lengkuas, memarkan",
            "1 cm jahe, memarkan",
            "3 lembar daun salam",
            "6 lembar daun jeruk, petik daunnya",
            "2 buah tomat, potong dadu",
            "1 sdt gula",
            "1.5 sdt garam",
            "4 sdm minyak sayur"
        ],
        cara: [],
    }, 
    {
        id: 14,
        nama: "Kue Ape",
        desc: "Kue Ape adalah camilan tradisional Betawi yang terbuat dari campuran tepung terigu, telur, santan, dan gula, yang kemudian dipanggang dalam cetakan khusus hingga matang dan berwarna keemasan. Rasanya manis gurih dengan tekstur yang lembut di tengah dan renyah di pinggirnya, sering dijumpai di pasar-pasar tradisional di Jakarta.",
        Kategori: "Kue, Tepung, Telur",
        image: "",
        bahan: [
            "100 g tepung beras",
            "50 g tepung terigu",
            "90 g gula pasir",
            "Sejumput garam",
            "1/2 sdt baking powder",
            "1/4 sdt soda kue",
            "2 sdm susu bubuk",
            "1 butir telur",
            "200 ml air",
            "3 tetes perisa pandan"
        ],
        cara: [],
    },
    {
        id: 15,
        nama: "Dodol Betawi",
        desc: "Dodol Betawi adalah kue tradisional khas Betawi yang terbuat dari campuran ketan, gula merah, santan, dan kelapa parut yang dimasak hingga mengental. Biasanya disajikan dalam bentuk blok padat dengan rasa manis yang khas dan aroma santan yang lezat. Dodol Betawi sering dijadikan sebagai oleh-oleh khas dari Jakarta.",
        Kategori: "Ketan, Santan",
        image: "",
        bahan: [
            "1 kg beras ketan",
            "700 g gula merah",
            "700 g gula pasir",
            "1 l santan",
            "4 lembar daun pandan"
        ],
        cara: [],
    },
    {
        id: 16,
        nama: "Kembang Goyang",
        desc: "Kembang Goyang adalah camilan ringan khas Betawi berupa adonan tepung beras yang digoreng hingga kembang dan berongga, kemudian disajikan dengan taburan gula halus. Rasanya renyah, manis, dan sering menjadi favorit di berbagai acara atau sebagai oleh-oleh khas dari Jakarta.",
        Kategori: "Manisan, Tepung, Santan, Telur",
        image: "",
        bahan: [
            "200 g tepung beras",
            "50 g tepung tapioka",
            "50 g tepung terigu",
            "100 g gula",
            "65 ml santan",
            "200 ml air putih",
            "2 butir telur",
            "1/2 sdt vanilla",
            "2 sdm margarin, dicairkan"
        ],
        cara: [],
    },
    {
        id: 17,
        nama: "Roti Buaya",
        desc: "Roti Buaya adalah makanan khas Betawi yang berbentuk seperti buaya dan terbuat dari campuran tepung terigu, gula, dan margarin yang digoreng hingga renyah. Rasanya manis dengan tekstur yang renyah di luar dan lembut di dalamnya, sering dijumpai di pasar tradisional atau acara-acara festival di Jakarta.",
        Kategori: "Manisan, Roti, Tepung, Telur",
        image: "",
        bahan: [
            "500 g tepung cakra",
            "1 sdm ragi",
            "1/2 sdt bread improver",
            "100 g gula pasir",
            "100 g margarin",
            "1 sdt garam",
            "2 butir telur",
            "Susu cair dingin"
        ],
        cara: [],
    },
    {
        id: 18,
        nama: "Kue Pancong (Kelapa)",
        desc: "Kue Pancong adalah jajanan tradisional Betawi berbentuk cawan dengan pinggiran yang bergerigi, terbuat dari campuran tepung beras, kelapa parut, gula, santan, dan sedikit garam, kemudian dipanggang hingga matang dan berwarna kecokelatan. Rasanya gurih, manis, dan harum kelapa, sering dijadikan camilan favorit di Jakarta.",
        Kategori: "Kue, Tepung, Santan, Kelapa",
        image: "",
        bahan: [
            "250 g tepung beras",
            "250 g kelapa setengah tua, kerok & parut memanjang",
            "700 ml santan sedang dari 1/2 butir kelapa",
            "5 sdm gula pasir",
            "1 sdt garam"
        ],
        cara: [],
    },
    {
        id: 19,
        nama: "Sayur Babanci",
        desc: "Sayur Babanci adalah hidangan khas Betawi yang terdiri dari campuran berbagai jenis sayuran seperti kacang panjang, terong, tahu, tempe, dan daun singkong yang dimasak dengan kuah santan kental yang diberi bumbu rempah seperti kemiri, lengkuas, dan kunyit. Rasanya gurih dan kaya akan rempah, sering disajikan sebagai lauk pendamping nasi dalam hidangan khas Betawi.",
        Kategori: "Sayur, Santan, Kelapa",
        image: "",
        bahan: [
            "500 g daging sapi, rebus dengan +/- 1 liter air",
            "50 g kelapa parut, sangrai lalu haluskan",
            "200 ml air santan sedang (1 bungkus santan instan 65 ml + air)",
            "300 ml air kelapa",
            "[Rempah (sangrai, haluskan)]",
            "1/2 sdt lada putih",
            "1/2 sdt ketumbar",
            "1/2 sdt jintan",
            "1/2 sdt biji kedaung",
            "1/2 botor",
            "[Bumbu Halus]",
            "5 buah cabai merah keriting",
            "5 butir bawang merah",
            "3 siung bawang putih",
            "2 butir kemiri sangrai",
            "1 ruas jempol kunyit (5 g)",
            "1 ruas jempol jahe (5 g)",
            "1 ruas jempol bangle (5 g)",
            "[Bumbu Lainnya]",
            "1 batang sereh",
            "3 lembar daun salam",
            "Garam secukupnya (+/- 1,5 sdt)",
            "Gula merah secukupnya (+/- 1 sdm)",
            "[Pelengkap]",
            "Ketupat",
            "Bawang Goreng",
            "Emping"
        ],
        cara: [],
    },
    {
        id: 20,
        nama: "Putu Mayang",
        desc: "Putu Mayang adalah hidangan manis tradisional dari Indonesia, terutama dikenal di daerah Betawi. Terbuat dari tepung beras yang dibentuk seperti mie halus, kemudian direbus hingga matang. Setelah matang, putu mayang disajikan dengan kuah santan yang manis dan pandan. Hidangan ini memiliki tekstur lembut dan aromanya yang khas, sering disajikan sebagai makanan penutup atau camilan.",
        Kategori: "Tepung, Santan",
        image: "",
        bahan: [
            "150 g tepung beras",
            "50 g tepung tapioka",
            "1/2 sdt garam",
            "300 ml santan",
            "Pewarna hijau dan merah",
            "[Syrup Gula Merah]",
            "150 g gula merah",
            "50 g gula pasir",
            "500 ml santan encer",
            "1/2 sdt garam",
            "1 lembar daun pandan"
        ],
        cara: [],
    },
];

module.exports = Food;