    const Food = [
        {
            id: 1,
            nama: "Soto Betawi",
            desc: "Soto Betawi adalah hidangan khas Jakarta berupa sup berkuah santan yang kaya akan rempah, disajikan dengan potongan daging sapi atau jeroan, kentang, dan tomat. Rasanya gurih dan lezat, sering dinikmati dengan tambahan emping, bawang goreng, dan perasan jeruk limau.",
            Kategori: ["Kuah", "Santan"],
            image: "../../../../public/assets/img/SotoBetawi.jpg",
            bahan: [
                "500 g daging sapi has bagian sandung lamur, potong-potong",
                "200 g babat sapi, rebus, potong 2 * 2 cm", 
                "200 g paru sapi, rebus, potong 2 * 2 cm",
                "3 sdm kecap manis",
                "3 cm kayumanis",
                "1 sdt pala bubuk",
                "4 buah cengkeh utuh",
                "3 buah batang serai, memarkan",
                "5 buah daun jeruk, buang tulang, iris memanjang",
                "2 cm lengkuas, memarkan",
                "4 sdt garam",
                "2 lembar daun salam",
                "1 sdt gula pasir",
                "1/2 sdt merica bubuk",
                "500 ml santan dari 1 butir kelapa",
                "2 sdm minyak",
                "2 l air",
                "[Bumbu Halus]",
                "12 butir bawang merah",
                "6 siung bawang putih",
                "3 buah kemiri, disangrai",
                "2 cm jahe",
                "1 sdt ketumbar bubuk",
                "[Bahan Pelengkap]",
                "2 buah tomat, potong dadu 2 cm",
                "2 batang daun bawang, iris tipis",
                "100 g bawang merah goreng",
                "50 g emping goreng",
                "4 buah jeruk nipis, belah jadi 2 bagian"
            ],
            cara: [
                "Rebus air dan daging hingga daging matang dan empuk. Potong dadu daging 3x3 cm",
                "Saring kaldu rebusan daging, didihkan kembali dengan daging, paru, dan babat",
                "Panaskan minyak, tumis bumbu halus bersama pala, cengkih, kayu manis, serai, lengkuas, daun jeruk, dan daun salam hingga harum. Tuang tumisan bumbu ke air rebusan daging, aduk rata. Masak dengan api sedang hingga mendidih",
                "Tuangkan santan, Bango Kecap Manis, garam, merica bubuk, dan gula pasir. Masak hingga matang",
                "Susun tomat dalam mangkuk, tuangkan soto, sajikan dengan bahan pelengkap lainnya"
            ],
            shortDesc: "Soto yang kaya akan rempah yang disajikan dengan daging dan jeroan",
            harga:"Rp8.000 - Rp85.000",
        },
        {
            id: 2,
            nama: "Ketoprak",
            desc: "Ketoprak adalah makanan khas Jakarta yang terdiri dari lontong, tahu goreng, bihun, dan tauge, disajikan dengan bumbu kacang yang gurih, kecap manis, dan taburan bawang goreng. Hidangan ini biasanya dilengkapi dengan kerupuk dan potongan mentimun untuk menambah kesegaran. ",
            Kategori: ["Sayur", "Kacang", "Tahu", "Lontong"],
            image: "../../../../public/assets/img/Ketoprak.jg",
            bahan: [
                "2 buah tahu putih",
                "2 buah ketupat, potong",
                "50 g taoge",
                "100 g bihun",
                "3 sdm kecap manis",
                "[Bumbu Kacang]",
                "150 g kacang tanah",
                "1 sdm gula merah, sisir",
                "1 siung bawang putih",
                "4 buah cabai rawit merah",
                "1/2 sdt garam",
                "2 sdm air asam jawa",
                "air secukupnya",
                "[Bahan Pelengkap]",
                "1 sdm bawang merah goreng",
                "kerupuk kuning"
            ],
            cara: [
                "Goreng tahu putih hingga berkulit dan blansir taoge dengan air panas. Kemudian, haluskan kacang tanah goreng, gula merah, cabai rawit merah dan bawang putih",
                "Tambahkan garam, air asam jawa, dan air matang secukupnya, lalu ulek kembali hingga bumbu kacang halus. Pindahkan ke mangkuk",
                "Ambil piring saji, susun dari bawah ke atas dengan urutan sebagai berikut: ketupat, taoge, tahu, dan bihun. Setelah semua bahan lengkap di piring, tuangkan bumbu kacang",
                "Tambahkan Bango Kecap Manis di atasnya. Terakhir, sajikan dengan taburan bawang goreng dan kerupuk"
            ],
            shortDesc: "Sayuran yang diulek bersama dengan saus kacang tanah, ketupat, dan tahu",
            harga:"Rp12.000 - Rp.25.000",
        },
        {
            id: 3,
            nama: "Sayur Besan",
            desc: "Sayur Besan adalah hidangan tradisional Betawi yang biasanya disajikan pada acara pernikahan, terdiri dari terubuk (bungkil bunga tebu), ebi, kentang, dan kacang panjang yang dimasak dalam kuah santan beraroma rempah. Rasanya gurih dan sedikit manis, mencerminkan kekayaan kuliner Betawi.",
            Kategori: ["Kuah", "Santan", "Sayur", "Lauk", "Pendamping"],
            image: "../../../../public/assets/img/sayur besan_L.jpg",
            bahan: [
                "8 batang telur terubuk/bunga tebu",
                "1 buah (200 g) kentang, kupas",
                "100 g buncis",
                "1 papan petai",
                "3 sdm minyak goreng",
                "3 lembar daun salam",
                "3 cm lengkuas, memarkan",
                "2 sdm ebi sangrai, biarkan utuh",
                "4 buah cabai merah, iris serong",
                "4 buah cabai hijau, iris serong",
                "1250 ml santan dari 1/2 butir kelapa",
                "2 batang daun bawang, iris 3 cm",
                "2 - 3 sdt garam",
                "2 sdt gula pasir",
                "10 g suun, siram air mendidih, potong 10 cm",
                "[Bumbu Halus]",
                "10 butir bawang merah",
                "3 siung bawang putih"
            ],
            cara: [
                " Kupas kulit telur terubuk, potong ujungnya, ambil isinya, potong serong menjadi 2 bagian. Potong kentang bentuk dadu 2 cm, dan potong buncis 2 cm. Kupas petai, belah-belah",
                "Panaskan minyak dalam wajan di atas api sedang, tumis bumbu halus, masukkan daun salam, lengkuas, dan ebi hingga berbau harum. Masukkan cabai merah dan hijau, aduk hingga layu. Tuang santan, masak hingga mendidih sambil ditimba-timba agar tidak pecah",
                "Masukkan telur terubuk, kentang, buncis, dan petai. Tambahkan garam dan gula, aduk",
                "Masukkan soun, aduk sebentar saja, aduk, angkat. Sajikan bersama nasi putih"
            ],
            shortDesc:"Sayuran yang berbahan dasar bungkil bunga tebu dan disajikan dengan kuah penuh rempah",
            harga:"Rp5.000 - Rp.50.000"
        },
        {
            id: 4,
            nama: "Asinan Betawi",
            desc: "Asinan Betawi adalah hidangan segar berupa campuran potongan buah-buahan seperti nanas, mangga muda, timun, dan kacang panjang yang direndam dalam larutan air asam yang manis pedas, biasanya disajikan dengan tambahan kerupuk dan bawang goreng sebagai pelengkap.",
            Kategori: ["Sayur", "Cemilan", "Pendamping"],
            image: "../../../../public/assets/img/Asinan.jpg",
            bahan: [
                "250 g tahu putih, kukus, potong dadu",
                "125 g mi kuning, rebus, tiriskan",
                "125 g mentimun, potong dadu",
                "125 g kol, iris tipis",
                "125 g daun selada",
                "100 g sawi asin",
                "75 g lokio",
                "75 g kacang tanah goreng tanpa kulit",
                "[Bumbu Halus]",
                "150 g kacang tanah goreng dengan kulit",
                "3 buah cabai rawit merah",
                "1 buah cabai merah besar",
                "1.5 sdt cuka",
                "1 sdt air jeruk nipis",
                "3 sdm gula pasir",
                "2 sdt Royco kaldu ayam",
                "[Bahan Saus]",
                "500 ml air",
                "3 sdm gula merah",
                "4 sdm kecap manis",
                "[Pelengkap]",
                "Bawang goreng",
                "Kerupuk mi",
                "Kerupuk merah"
            ],
            cara: [
                "Rebus air, gula merah, dan Kecap Manis sambil diaduk rata",
                "Masukkan bumbu halus termasuk Royco Kaldu Ayam ke dalam rebusan air, masak kembali hingga semua tercampur rata. Angkat dan sisihkan",
                "Tata tahu, mi kuning, mentimun, kol, daun selada, sawi asin, lokio, dan kacang tanah goreng ke atas piring saji. Tuang saus ke atasnya",
                "Sajikan bersama bawang goreng, kerupuk mi, dan kerupuk merah"
            ],
            shortDesc:"Makanan dengan campuran sayuran segar atau buah-buahan yang diasinkan, disiram dengan saus kacang pedas manis, dan ditaburi kerupuk serta kacang tanah goreng.",
            harga:"Rp13.000 - Rp20.000"
        },
        {
            id: 5,
            nama: "Kue Geplak",
            desc: "Kue Geplak adalah jajanan tradisional Jawa Tengah yang terbuat dari campuran kelapa parut, gula merah, dan tepung ketan yang kemudian dipadatkan dan dibentuk bulat pipih. Rasanya manis gurih dengan tekstur yang kenyal, sering menjadi pilihan camilan yang lezat di Indonesia.",
            Kategori: ["Kue", "Kelapa"],
            image: "../../../../public/assets/img/",
            bahan: [
                "1 kg tepung beras giling (atau tepung kemasan)",
                "1 butir kelapa parut",
                "300 g gula merah",
                "200 g gula pasir",
                "1 sdt garam",
                "600 ml air",
                "10 lembar daun pandan",
                "[Taburan] 100 g tepung beras sangrai]",
                ],
            cara:[
                "Sangrai tepung beras+5 lembar daun pandan dengan api kecil, sambil terus diaduk2 hingga tepung terasa ringan dan berubah warna sedikit kekuningan. *patokannya daun pandan akan sangat kering tanda tepung sudah matang. Angkat dan sisihkan",
                "Sangrai kelapa dengan api kecil sambil terus di aduk2 hingga kelapa berubah menjadi kuning kecoklatan. Angkat dan sisihkan",
                "Rebus air+gula merah+gula pasir+5lembar daun pandan hingga gula larut dan mendidih. angkat dan saring lalu sisihkan",
                "Penyelesaian: Campur jadi satu tepung sangrai+garam+kelapa sangrai aduk rata lalu masukkan air gula sedikit demi sedikit sambil di aduk rata hingga adonan bila di kepal bisa menyatu, hentikan pemakaian air gula",
                "Setelah adonan semua tercampur rata, cetak dalam wadah, Cetak dan padatkan. Diamkan hingga geplak dingin lalu tabur dengan sedikit tepung beras sangrai",
                "setelah dingin, siap dipotong-potong dan di sajikan"
            ],
            shortDesc:"Camilan kelapa yang dipadukan dengan gula merah dan tepung ketan.",
            harga:"Rp25.000 - Rp50.000",
        },
        {
            id: 6,
            nama: "Nasi Ulam",
            desc: " Nasi Ulam adalah hidangan nasi yang dicampur dengan rempah-rempah, daun-daunan segar seperti daun kemangi, daun jeruk purut, dan daun serai, serta bumbu-bumbu lainnya seperti serai, lengkuas, dan bawang merah yang diuleg hingga harum. Biasanya disajikan dengan lauk seperti ayam goreng, ikan bakar, atau tempe goreng.",
            Kategori: ["Nasi", "Lauk", "Bihun"],
            image: "../../../../public/assets/img/NasiUlam.jpg",
            bahan: [
                "[Nasi]",
                "2 gelas beras",
                "2 gelas air",
                "1 cm serai, memarkan",
                "1/4 sdt garam",
                "1 sdm minyak",
                "[Serundeng]",
                "200 g kelapa, parut memanjang",
                "100 g gula merah, sisir halus",
                "2 lembar daun salam",
                "3 cm lengkuas, memarkan",
                "50 ml air",
                "[Bumbu Halus untuk Serundeng]",
                "1 sdm ketumbar, sangrai",
                "2 siung bawang putih",
                "3 siung bawang merah",
                "1/2 sdt garam",
                "[Semur]",
                "5 potong tahu putih",
                "1/2 cm kayu manis",
                "Secuil kecil buah pala",
                "3 sdm kecap manis",
                "100 ml air",
                "[Bumbu Halus untuk Semur]",
                "2 siung bawang putih",
                "3 siung bawang merah",
                "2 butir kemiri",
                "1/4 sdt garam",
                "1/4 sdt merica",
                "[Bihun Goreng]",
                "1/2 bungkus bihun, rendam air panas lalu tiriskan",
                "1 buah wortel, potong bulat",
                "6 lembar daun kol, sobek kasar",
                "2 sdm kecap manis",
                "[Bumbu Halus untuk Bihun Goreng]",
                "2 siung bawang putih",
                "1 butir kemiri",
                "1/4 sdt garam",
                "1/4 sdt merica",
                "[Telur Dadar]",
                "2 butir telur ayam, kocok lepas",
                "1/4 sdt garam",
                "1/4 sdt merica"
            ],
            cara: [
                "Masak beras dengan air sampai setengah matang (jadi nasi aron)",
                "Masukkan lengkuas, daun salam, garam, dan minyak goreng ke dalamnya (nasi setengah matang atau aron tadi). Aduk rata",
                "Lanjutkan memasak nasi hingga benar-benar matang",
                "Dalam wajan, masukkan semua bahan serundeng dan bumbu halusnya. Aduk-aduk dan masak hingga airnya menyusut. Koreksi rasanya",
                "Lanjutkan memasak atau sangrai serundeng hingga kering dan berwarna kecoklatan. Aduk terus sampai parutan kelapa terasa ringan. Angkat",
                "Panaskan sedikit minyak. Tumis bumbu halus bersama kayu manis dan pala hingga harum",
                "Tuang air dan masukkan tahu putih. Aduk perlahan dan pastikan tahu terendam sempurna dalam air",
                "Tambahkan kecap manis. Aduk perlahan lalu koreksi rasanya",
                "Lanjutkan masak semur sampai kuah mengental dan sedikit menyusut. Angkat",
                "Panaskan sedikit minyak. Tumis bumbu halus hingga harum",
                "Masukkan wortel dan kol. Masak hingga empuk",
                "Masukkan bihun dan kecap manis. Aduk hingga tercampur rata dan matang. Angkat",
                "Kocok lepas telur dengan garam dan merica",
                "Dadar telur melebar ke permukaan wajan. Masak hingga matang kedua sisinya. Angkat",
                "Dadar telur melebar ke permukaan wajan. Masak hingga matang kedua sisinya. Angkat",
                "Tata nasi di atas piring saji",
                "Beri lauk serundeng, semur tahu, bihun goreng, dan telur dadar",
                "Siap disajikan",
            ],
            shortDesc: "Nasi yang disajikan dengan berbagai macam lauk-pauk seperti serundeng, dendeng, telur, dan ditambah dengan sambal serta kerupuk.",
            harga:"Rp20.000 - Rp50.000"
        },
        {
            id: 7,
            nama: "Semur Jengkol",
            desc: "Semur Jengkol adalah hidangan khas Betawi yang terbuat dari jengkol yang dimasak dengan bumbu rempah seperti bawang merah, bawang putih, ketumbar, dan lengkuas, serta tambahan gula merah, kecap manis, dan santan untuk menciptakan kuah kental beraroma. Rasanya gurih manis dengan aroma rempah yang khas, sering disajikan sebagai lauk pendamping nasi.",
            Kategori: ["Semur", "Jengkol", "Pedas", "Lauk"],
            image: "../../../../public/assets/img/SemurJengkol.jpg",
            bahan: [
                "300 g jengkol tua",
                "6 butir bawang merah, iris tipis",
                "2 lembar daun salam",
                "5 sdm kecap manis",
                "1 sdm gula merah, sisir",
                "1 gelas air",
                "garam secukupnya",
                "[Bumbu Halus]",
                "3 siung bawang putih",
                "2 butir kemiri",
                "10 cabe merah keriting",
                "5 cabe rawit",
                "1/2 sdm ketumbar",
                "1/2 sdt merica butiran",
                "1/4 buah pala",
                "Sejumput jinten"
            ],
            cara: [
                "Cuci jengkol, belah lalu rebus dengan air cucian beras sampai empuk (tujuannya untuk menghilangkan bau menyengat pada jengkol)",
                "Setelah jengkol empuk angkat, bilas dengan air bersih bila perlu, tiriskan lalu memarkan",
                "Tumis bawang merah iris sampai matang kecoklatan, masukkan bumbu halus, tomat dan daun salam, aduk rata sampai bumbu matang, masukkan jengkol, tuangi air, biarkan mendidih lalu masukkan garam, gula merah dan kecap manis, masak sampai bumbu meresap, koreksi rasa, bila sudah pas matikan api, sajikan",
            ],
            shortDesc: "Jengkol yang dimasak dalam kuah kecap manis dengan bumbu rempah-rempah menghasilkan rasa gurih dan sedikit manis dengan aroma khas.",
            harga:"Rp20.000 - Rp40.000"
        },
        {
            id: 8,
            nama: "Ayam Sampyok",
            desc: "Ayam Sampyok adalah hidangan khas Betawi yang terdiri dari potongan ayam yang dimarinasi dengan bumbu rempah seperti bawang merah, bawang putih, jahe, kunyit, dan kemiri, lalu dipanggang atau dibakar hingga matang dengan aroma harum yang khas. Biasanya disajikan dengan sambal dan lalapan sebagai pelengkap.",
            Kategori: ["Ayam", "Kacang", "Santan"],
            image: "../../../../public/assets/img/AyamSamyok.jpg",
            bahan: [
                "1 ekor ayam, belah bagian dada, lebarkan",
                "[Bahan Marinasi]",
                "Lemon/Jeruk nipis",
                "1/2 sdt garam",
                "[Bumbu Iris]",
                "3 batang serai, ambil bagian putih",
                "3 siung bawang putih",
                "3 butir bawang merah",
                "[Bumbu Halus]",
                "15 buah cabai keriting merah",
                "10 buah rawit oranye",
                "5 butir kemiri sangrai",
                "7 siung bawang putih",
                "7 butir bawang merah",
                "1 jari kunyit",
                "1 ruas jahe",
                "1 sdt lada",
                "1 sdm ketumbar",
                "100 g kacang tanah goreng",
                "[Bumbu Cemplung]",
                "3 lembar daun salam",
                "5 lembar daun jeruk, sobek-sobek",
                "5 ruas jari lengkuas, memarkan",
                "1,5 sdt garam",
                "1 sdt kaldu jamur",
                "2 ibu jari gula merah",
                "500 ml santan",
                "[Pelengkap]",
                "Sambal dan lalap"
            ],
            cara: [
                "Marinasi ayam dengan jeruk nipis/lemon dan garam. Diamkan sekitar 1/2 jam",
                "Tumis bumbu iris sampai harum. Masukkan bumbu halus (kecuali kacang tanah), teruskan menumis. Masukkan bumbu cemplung, teruskan menumis. Tambahkan kacang tanah goreng yang sudah dihaluskan",
                "Masukkan ayam, aduk rata. Tuang santan, aduk-aduk, tutup, didihkan. Koreksi rasa. Ungkep sampai ayam empuk dan bumbu meresap",
                "Panggang/bakar ayam dengan arang atau grill pan sambil olesi sisa bumbu ungkep. Angkat, sajikan bersama pelengkap",
            ],
            shortDesc: "Ayam yang dimasak dengan bumbu rempah-rempah serta santan yang menghasilkan rasa gurih dan kaya rempah.",
            harga:"Rp25.000 - Rp50.000"
        },
        {
            id: 9,
            nama: "Nasi Kebuli",
            desc: "Nasi Kebuli adalah hidangan nasi yang berasal dari Timur Tengah namun populer di Indonesia, terdiri dari nasi yang dimasak dengan rempah-rempah seperti kayu manis, cengkeh, dan kapulaga, kemudian ditambahkan dengan potongan daging kambing atau domba yang diolah dengan bumbu khusus dan kacang-kacangan. Rasanya gurih, harum rempah, dan dagingnya lembut, sering disajikan dalam acara-acara spesial.",
            Kategori: ["Nasi", "Daging", "Sapi"],
            image: "../../../../public/assets/img/NasiKebuli.jpg",
            bahan: [
                "400 g daging sapi has dalam potong dadu",
                "800 g beras bulir panjang",
                "100 g bawang bombay",
                "5 cm kayu manis",
                "1/2 sdt pala bubuk",
                "2 g cengkeh",
                "4 buah kapulaga",
                "4 sdm margarin",
                "1 sdt garam",
                "1 sdt Royco kaldu sapi",
                "3 sdm kismis",
                "[Bumbu Halus]",
                "10 buah bawang merah",
                "4 siung bawang putih",
                "4 cm jahe",
                "1/2 sdm ketumbar disangrai",
                "1/2 sdt merica putih butir disangrai",
                "1/2 sdt jintan",
                "[Pelengkap]",
                "3 sdm bawang merah goreng",
                "Acar nanas"
            ],
            cara: [
                "Panaskan margarin, tumis bumbu halus, bawang bombay, kayu manis, pala, cengkih, dan kapulaga hingga harum",
                "Masukkan daging sapi, aduk rata. Masak hingga daging kaku. Masukkan beras, aduk rata",
                "Tuang air, garam, dan Royco Kaldu Sapi, aduk. Masak hingga air terserap habis, tambahkan kismis, aduk rata. Angkat",
                "Kukus dalam dandang panas hingga matang. Angkat",
                "Sajikan bersama pelengkap",
            ],
            shortDesc: "Nasi yang dimasak dengan kaldu daging kambing atau ayam, susu, dan aneka rempah dan disajikan dengan potongan daging kambing atau ayam goreng.",
            harga:"Rp25.000 - Rp100.000"
        },
        {
            id: 10,
            nama: "Nasi Uduk Betawi",
            desc: "Nasi Uduk adalah hidangan khas Betawi yang terdiri dari nasi yang dimasak dengan santan, serai, daun salam, dan daun jeruk, memberikan aroma harum yang khas. Biasanya disajikan dengan pelengkap seperti ayam goreng, telur, tempe goreng, sambal, dan krupuk, menjadi hidangan sarapan atau makanan sehari-hari yang populer di Jakarta.",
            Kategori: ["Nasi", "Kentang", "Tempe", "Semur"],
            image: "../../../../public/assets/img/NasiUduk.jpg",
            bahan: [
                "[Nasi]",
                "400 g beras",
                "600 ml santan",
                "3 lembar daun salam",
                "1 batang serai, geprek",
                "2 cm jahe, geprek",
                "2 cm lengkuas, geprek",
                "Garam secukupnya",
                "[Sambal Kacang]",
                "2 buah cabe merah besar, goreng",
                "3 buah cabe rawit, goreng",
                "2 siung bawang putih, goreng",
                "150 g kacang tanah, goreng",
                "1/4 sdt cuka",
                "1 sdt gula",
                "1/2 sdt garam",
                "100 ml air panas",
                "[Perkedel Kentang]",
                "500 g kentang, potong-potong kemudian goreng sampai matang dan haluskan",
                "1 batang daun bawang, iris halus",
                "4 siung bawang merah, goreng",
                "2 siung bawang putih, goreng",
                "3/4 sdt garam",
                "1/2 sdt merica bubuk",
                "1 butir telur, kocok lepas",
                "Minyak untuk menggoreng secukupnya",
                "[Semur Tahu & Telur]",
                "4 buah tahu, potong masing-masing menjadi 2 bagian dan goreng hingga matang",
                "4 butir telur ayam, rebus",
                "5 sdm minyak untuk menumis",
                "150 ml air",
                "1/2 buah tomat, potong-potong",
                "1 batang serai, geprek",
                "[Bumbu Halus]",
                "3 siung bawang merah",
                "3 siung bawang putih",
                "1/4 sdt merica",
                "3 butir kemiri, sangrai",
                "1/2 sdt garam",
                "1/2 sdt gula",
                "[Orek Tempe]",
                "250 g tempe, iris tipis kotak",
                "4 siung bawang merah, iris tipis",
                "4 siung bawang putih, iris tipis",
                "3 buah cabe merah besar, iris serong",
                "1 ruas lengkuas, geprek",
                "2 batang sereh, geprek",
                "2 lembar daun salam",
                "1 sdm gula merah, sisir halus",
                "3 sdm gula pasir",
                "3 sdm air asam jawa",
                "1 sdt garam",
                "50 ml air",
                "Minyak untuk menggoreng secukupnya"
            ],
            cara: [
                "Cuci beras hingga bersih, lalu kukus sampai setengah matang, sisihkan",
                "Rebus santan. Tambahkan daun salam, jahe, lengkuas, dan garam, masak hingga mendidih. Masukkan beras, aduk aduk lalu matikan apinya",
                "Aduk terus sampai santan terserap habis. Kukus beras selama 30 menit atau sampai matang",
                "Giling atau tumbuk halus cabe merah, cabe rawit, bawang putih, dan kacang tanah",
                "Lalu tuang air panas, cuka, garam, dan gula, aduk hingga merata",
                "Haluskan bawang merah dan bawang putih goreng",
                "Masukkan kentang goreng tumbuk, aduk hingga merata",
                "Masukkan daun bawang, garam, dan merica bubuk. Aduk hingga merata. Icip dan sesuaikan rasanya",
                "Bentuk adonan perkedel menjadi bola-bola dengan tangan, sambil dipadatkan supaya tidak pecah saat digoreng. Pipihkan kemudian celupkan ke kocokan telur",
                "Goreng dalam minyak panas hingga coklat keemasan",
                "angkat dan tiriskan",
                "Siap disajikan",
            ],
            shortDesc:"Nasi yang dimasak dengan santan dan aneka rempah seperti yang menghasilkan nasi yang gurih dan wangi dan disajikan dengan lauk-pauk.",
            harga:"Rp10.000 - Rp 30.000"
        },    
        {
            id: 11,
            nama: "Laksa Betawi",
            desc: "Laksa Betawi adalah hidangan khas Betawi yang terdiri dari mie tebal yang disajikan dalam kuah santan beraroma rempah seperti kunyit, ketumbar, dan lengkuas, ditambahkan dengan potongan daging sapi, telur rebus, tauge, kacang panjang, dan kadang-kadang jeroan. Rasanya kaya dan gurih dengan sentuhan pedas dan segar, sering dihidangkan dengan perasan jeruk nipis dan emping sebagai tambahan.",
            Kategori: ["Kuah", "Kaldu", "Ayam"],
            image: "../../../../public/assets/img/",
            bahan: [
                "1/2 ekor ayam kampung",
                "1200 ml air, untuk merebus",
                "250 g udang kupas",
                "2 batang serai, memarkan",
                "2 lembar daun jeruk",
                "1 sdt Royco Kaldu Ayam",
                "200 ml susu rendah lemak",
                "2 sdm minyak, untuk menumis",
                "[Bumbu Halus]",
                "8 butir bawang merah",
                "4 siung bawang putih",
                "4 butir kemiri, sangrai",
                "4 cm kunyit",
                "1 sdt ketumbar butiran",
                "1/4 sdt jintan bubuk",
                "1 sdm ebi",
                "1 sdt garam",
                "[Pelengkap]",
                "200 g bihun kering, seduh air panas, tiriskan",
                "100 g taoge, seduh air panas, tiriskan",
                "4 butir telur rebus, belah 2",
                "Daun kemangi",
                "Bawang goreng",
                "Sambal rawit",
                "Jeruk limau",
                "Kecap manis"
            ],
            cara:[
                "Tumis bumbu halus hingga harum.",
                "Masukkan daun jeruk, serai, dan daun salam. Tumis hingga layu.",
                "Masukkan potongan ayam dan udang ke dalam tumisan bumbu, aduk hingga berubah warna.",
                "Tuangkan air kaldu ayam, masak hingga mendidih dan ayam matang.",
                "Tambahkan santan ke dalam panci, aduk perlahan agar santan tidak pecah. Masak dengan api kecil hingga mendidih.",
                "Siapkan bihun yang sudah direndam dan tauge dalam mangkuk saji.",
                "Tuang kuah laksa beserta ayam dan udang ke dalam mangkuk.",
                "Taburi dengan irisan daun bawang dan pelengkap lainnya seperti telur rebus, daun kemangi, sambal rawit, dan jeruk limau.",
                "Laksa Betawi siap disajikan dan dinikmati selagi hangat.",
            ],
            shortDesc:"Mie khas Jakarta yang disajikan dalam kuah kuning santan kental, dimasak dengan bumbu-bumbu serta dilengkapi dengan topping seperti ayam, telur rebus, dan emping melinjo.",
            harga:"Rp15.000 - Rp50.000"
        },
        {
            id: 12,
            nama: "Kerak Telor",
            desc: "Kerak Telor adalah makanan khas Betawi berupa adonan tepung beras yang digoreng dengan telur ayam dan bumbu-bumbu seperti ebi, bawang merah, dan kelapa parut, kemudian disajikan dengan taburan bawang goreng dan serundeng. Rasanya gurih dengan aroma harum yang khas, sering dijumpai di festival atau acara khusus di Jakarta seperti Pekan Raya Jakarta (PRJ).",
            Kategori: ["Telur", "Lauk", "Kelapa"],
            image: "../../../../public/assets/img/KerakTelor.jpg",
            bahan: [
                "100 g beras ketan, bersihkan dan rendam dalam air selama 2 jam",
                "5 butir telur bebek",
                "5 sdm bubuk ebi",
                "5 sdm garam",
                "5 sdm bawang goreng",
                "5 sdm serundeng",
                "2,5 sdm gula",
                "5 butir cabai",
                "2,5 sdt bubuk merica"
            ],
            cara:[
                "Rendam beras ketan putih dalam air selama beberapa jam atau semalaman.",
                "Siapkan wajan cekung kecil untuk memasak.",
                "Panaskan wajan tanpa minyak di atas api sedang dan masukkan satu sendok sayur beras ketan yang sudah direndam, tiriskan, dan masukkan ke dalam wajan panas. Ratakan beras ketan di permukaan wajan.",
                "Tambahkan sedikit air di atas beras ketan dan masak hingga setengah matang.",
                "Pecahkan telur (ayam atau bebek) dan campurkan dengan bumbu halus yang terdiri dari bawang merah, bawang putih, cabai, kencur, jahe, dan garam.",
                "Kocok telur hingga tercampur rata dengan bumbu.",
                "Tuangkan campuran telur di atas ketan yang sudah setengah matang di wajan.",
                "Biarkan telur dan ketan matang perlahan di atas api. Tutup wajan jika diperlukan untuk memastikan telur matang sempurna.",
                "Setelah bagian bawah kerak telor matang dan sedikit kecokelatan, balik wajan sehingga kerak telor terpanggang langsung di atas api (menggunakan wajan yang bisa dibalik atau dengan teknik membalik manual).",
                "Masak hingga bagian atasnya matang dan sedikit gosong.",
                "Taburkan serundeng dan ebi  di atas kerak telor yang sudah matang.",
                "Angkat kerak telor dari wajan dan letakkan di atas piring saji.",
                "Kerak telor siap disajikan saat masih panas."
            ],
            shortDesc:"Beras ketan yang dimasak dengan telur ayam atau telur bebek, dicampur dengan kelapa parut sangrai dan bumbu halus, kemudian dimasak hingga garing di atas wajan besi dan disajikan dengan taburan serundeng dan bawang goreng.",
            harga:"Rp30.000 - Rp 50.000"
        },
        {
            id: 13,
            nama: "Gabus Pucung",
            desc: "Gabus Pucung adalah hidangan khas Betawi yang terdiri dari ikan gabus yang digoreng dan disajikan dengan bumbu pedas manis yang terbuat dari cabai, bawang merah, bawang putih, dan gula merah yang dimasak hingga mengental. Rasanya pedas, manis, dan gurih dengan tekstur ikan yang lembut, sering menjadi hidangan favorit di warung makan Betawi.",
            Kategori: ["Ikan", "Santan", "Pedas"],
            image: "../../../../public/assets/img/",
            bahan: [
                "1 ekor ikan gabus",
                "2 sdm air jeruk nipis",
                "1 sdt garam",
                "750 ml air",
                "3 sdm kecap manis",
                "1 sdm bawang merah goreng",
                "300 ml minyak sayur",
                "[Marinasi Ikan, haluskan]",
                "4 siung bawang putih",
                "3 sdt ketumbar butiran, sangrai",
                "2 buah jeruk nipis, peras",
                "1/2 sdt garam",
                "[Bumbu Halus]",
                "12 butir bawang merah",
                "8 siung bawang putih",
                "6 buah cabai merah keriting",
                "3 cm kunyit",
                "6 buah kluwek, ambil isinya",
                "4 butir kemiri, sangrai",
                "[Pelengkap Ikan Gabus]",
                "1 buah jeruk limau",
                "1 batang daun bawang, iris serong",
                "7 buah cabai rawit merah",
                "4 buah serai, memarkan",
                "3 cm lengkuas, memarkan",
                "1 cm jahe, memarkan",
                "3 lembar daun salam",
                "6 lembar daun jeruk, petik daunnya",
                "2 buah tomat, potong dadu",
                "1 sdt gula",
                "1.5 sdt garam",
                "4 sdm minyak sayur"
            ],
        cara: [
            "Bersihkan ikan gabus, buang isi perutnya, lalu potong-potong sesuai selera.",
            "Lumuri ikan dengan garam dan jeruk nipis, diamkan selama 15 menit untuk menghilangkan bau amis. Bilas hingga bersih.",
            "Panaskan minyak dalam wajan.",
            "Goreng potongan ikan gabus hingga matang dan berwarna kecokelatan. Angkat dan tiriskan.",
            "Haluskan bawang merah, bawang putih, kemiri, cabai merah, jahe, dan kunyit.",
            "Tumis bumbu halus dalam sedikit minyak hingga harum.",
            "Masukkan daun salam, daun jeruk, dan serai yang sudah dimemarkan. Tumis hingga bumbu matang.",
            "Tambahkan air ke dalam tumisan bumbu. Biarkan mendidih.",
            "Masukkan kluwek yang sudah dihaluskan. Aduk hingga tercampur rata dan kuah berubah warna menjadi hitam.",
            "Tambahkan garam dan gula merah sesuai selera.",
            "Masukkan potongan ikan gabus yang sudah digoreng ke dalam kuah.",
            "Masak dengan api kecil hingga ikan benar-benar menyerap bumbu dan kuah sedikit mengental.",
            "Angkat dan sajikan Gabus Pucung dalam mangkuk saji.",
            "Taburi dengan bawang goreng dan daun bawang iris sebagai hiasan.",
        ],
        shortDesc: "Ikan gabus yang digoreng dengan bumbu rempah khas, disajikan bersama dengan pucung, yaitu lontong dengan taburan kuah kari yang lezat.",
        harga:"Rp15.000 - Rp 30.000"
        }, 
        {
            id: 14,
            nama: "Kue Ape",
            desc: "Kue Ape adalah camilan tradisional Betawi yang terbuat dari campuran tepung terigu, telur, santan, dan gula, yang kemudian dipanggang dalam cetakan khusus hingga matang dan berwarna keemasan. Rasanya manis gurih dengan tekstur yang lembut di tengah dan renyah di pinggirnya, sering dijumpai di pasar-pasar tradisional di Jakarta.",
            Kategori: ["Kue", "Tepung", "Telur"],
            image: "../../../../public/assets/img/KueApe.jpg",
            bahan: [
                "100 g tepung beras",
                "50 g tepung terigu",
                "90 g gula pasir",
                "Sejumput garam",
                "1/2 sdt baking powder",
                "1/4 sdt soda kue",
                "2 sdm susu bubuk",
                "1 butir telur",
                "200 ml air",
                "3 tetes perisa pandan"
            ],
            cara:[
                "Campurkan tepung beras, tepung terigu, gula pasir, baking powder, vanili bubuk, dan garam dalam satu wadah besar. Aduk rata.",
                "Tuangkan santan hangat sedikit demi sedikit sambil terus diaduk hingga adonan menjadi lembut dan tidak bergerindil.",
                "Masukkan telur yang sudah dikocok lepas ke dalam adonan, aduk hingga tercampur rata.",
                "Tambahkan pperisa hijau pandan sesuai selera, aduk hingga warna merata.",
                "Diamkan adonan selama sekitar 30 menit agar baking powder bereaksi dan adonan mengembang.",
                "Panaskan cetakan kue ape atau wajan kecil di atas api sedang. Olesi sedikit minyak goreng agar kue tidak lengket.",
                "Tuang satu sendok sayur adonan ke dalam cetakan atau wajan, putar-putar agar adonan merata dan membentuk pinggiran yang tipis.",
                "Tutup cetakan atau wajan dan masak hingga bagian tengahnya matang dan bagian pinggirnya renyah. Biasanya membutuhkan waktu sekitar 3-5 menit.",
                "Angkat kue ape dari cetakan atau wajan menggunakan spatula.",
                "Kue ape siap disajikan hangat sebagai camilan.",
            ],
            shortDesc:"Kue yang terdiri campuran tepung beras, gula merah, dan kelapa parut yang dibungkus dalam daun pisang, kemudian dipanggang hingga matang, memberikan cita rasa manis dan tekstur yang lembut.",
            harga:"Rp5.000 - Rp10.000"
        },
        {
            id: 15,
            nama: "Dodol Betawi",
            desc: "Dodol Betawi adalah kue tradisional khas Betawi yang terbuat dari campuran ketan, gula merah, santan, dan kelapa parut yang dimasak hingga mengental. Biasanya disajikan dalam bentuk blok padat dengan rasa manis yang khas dan aroma santan yang lezat. Dodol Betawi sering dijadikan sebagai oleh-oleh khas dari Jakarta.",
            Kategori: ["Ketan", "Santan"],
            image: "../../../../public/assets/img/Dodol.jpg",
            bahan: [
                "1 kg beras ketan",
                "700 g gula merah",
                "700 g gula pasir",
                "1 l santan",
                "4 lembar daun pandan"
            ],
            cara: [
                "Serut halus gula merah untuk memudahkan proses pencampuran.",
                "Campurkan tepung ketan dengan santan encer dalam wadah besar. Aduk hingga tidak ada tepung yang menggumpal.",
                "Tambahkan santan kental ke dalam campuran tersebut, aduk rata.",
                "Siapkan wajan besar atau kuali, panaskan dengan api sedang.",
                "Tuang adonan tepung ketan dan santan ke dalam wajan.",
                "Masukkan gula merah serut, garam, dan daun pandan. Aduk rata.",
                "Masak adonan dengan api kecil sambil terus diaduk tanpa henti. Proses ini membutuhkan waktu yang cukup lama, sekitar 4-5 jam, agar adonan tidak gosong dan matang merata. Pastikan adonan berubah menjadi kental dan kenyal.",
                "Setelah adonan dodol berwarna cokelat tua dan mengental, angkat dan matikan api.",
                "Siapkan loyang atau tampah yang telah diolesi sedikit minyak agar dodol tidak lengket.",
                "Tuang adonan dodol ke dalam loyang atau tampah, ratakan permukaannya.",
                "Biarkan dodol dingin dan mengeras.",
                "Setelah dodol dingin, potong-potong sesuai selera.",
                "Bungkus dodol dengan plastik atau daun pisang untuk penyimpanan."
            ],
            shortDesc:"Camilan yang dari campuran santan, gula merah, tepung beras, dan rempah-rempah, yang kemudian dikukus hingga mengental dan memiliki tekstur kenyal serta manis yang khas.",
            harga:"Rp10.000 - Rp40.000"
        },
        {
            id: 16,
            nama: "Kembang Goyang",
            desc: "Kembang Goyang adalah camilan ringan khas Betawi berupa adonan tepung beras yang digoreng hingga kembang dan berongga, kemudian disajikan dengan taburan gula halus. Rasanya renyah, manis, dan sering menjadi favorit di berbagai acara atau sebagai oleh-oleh khas dari Jakarta.",
            Kategori: ["Manisan", "Tepung", "Santan", "Telur"],
            image: "../../../../public/assets/img/KembangGoyang.jpg",
            bahan: [
                "200 g tepung beras",
                "50 g tepung tapioka",
                "50 g tepung terigu",
                "100 g gula",
                "65 ml santan",
                "200 ml air putih",
                "2 butir telur",
                "1/2 sdt vanilla",
                "2 sdm margarin, dicairkan"
            ],
            cara: [
                "Campur tepung beras, tepung terigu, dan garam dalam sebuah mangkuk besar. Aduk hingga tercampur rata.",
                "Tambahkan air sedikit demi sedikit ke dalam campuran tepung sambil terus diaduk hingga membentuk adonan yang agak kental. Pastikan adonan tidak terlalu encer.",
                "Panaskan minyak dalam wajan dengan api sedang hingga cukup panas. Pastikan wajan cukup dalam untuk memungkinkan kembang goyang mengembang dengan baik.",
                "Tuang adonan ke dalam corong kembang goyang. Tekan corong di atas wajan yang telah dipanaskan, lalu putar corong dengan cepat sehingga adonan menetes ke dalam minyak panas. Lakukan gerakan memutar secara cepat agar adonan membentuk pola kembang goyang.",
                "Goreng kembang goyang hingga keemasan dan renyah. Pastikan untuk membaliknya agar matang secara merata.",
                "Setelah kembang goyang matang, angkat dari minyak panas dan tiriskan di atas kertas minyak atau tisu dapur untuk menghilangkan sisa minyak.",
                "Biarkan kembang goyang dingin sebelum disajikan. Setelah dingin, Anda bisa menyimpannya dalam wadah kedap udara untuk menjaga kelezatannya.",
                "Kembang goyang siap disajikan sebagai camilan atau makanan ringan yang lezat!",
            ],
            shortDesc:"Camilan yang dari adonan tepung beras yang digoreng hingga berbentuk kembang dan ditaburi dengan gula halus, memberikan cita rasa manis renyah yang nikmat.",
            harga:"Rp5.000 - Rp 15.000"
        },
        {
            id: 17,
            nama: "Roti Buaya",
            desc: "Roti Buaya adalah makanan khas Betawi yang berbentuk seperti buaya dan terbuat dari campuran tepung terigu, gula, dan margarin yang digoreng hingga renyah. Rasanya manis dengan tekstur yang renyah di luar dan lembut di dalamnya, sering dijumpai di pasar tradisional atau acara-acara festival di Jakarta.",
            Kategori: ["Manisan", "Roti", "Tepung", "Telur"],
            image: "../../../../public/assets/img/",
            bahan: [
                "500 g tepung cakra",
                "1 sdm ragi",
                "1/2 sdt bread improver",
                "100 g gula pasir",
                "100 g margarin",
                "1 sdt garam",
                "2 butir telur",
                "Susu cair dingin"
            ],
            cara: [
                "Campurkan ragi dengan susu cair dingin dalam mangkuk kecil. Biarkan selama beberapa menit sampai ragi aktif dan berbusa.",
                "Dalam mangkuk besar, campur tepung cakra, gula pasir, bread improver (jika digunakan), dan garam. Aduk rata.",
                "Tambahkan campuran ragi yang sudah diaktifkan dan telur ke dalam campuran tepung. Aduk menggunakan spatula atau sendok kayu.",
                "Setelah tercampur, tambahkan margarin yang sudah dilelehkan ke dalam adonan. Uleni adonan hingga elastis dan tidak lengket di tangan. Jika adonan terlalu kering, tambahkan sedikit susu cair dingin.",
                "Tutup mangkuk dengan kain bersih atau plastik wrap. Biarkan adonan fermentasi selama sekitar 1-2 jam, atau hingga mengembang dua kali lipat.",
                "Setelah adonan mengembang, bagi adonan menjadi beberapa bagian kecil. Ambil satu bagian adonan, pipihkan dan beri isi sesuai selera. Bentuk adonan menjadi seperti buaya dengan menciptakan bentuk kepala, badan, dan ekor. Gunakan pisau untuk memberi detail seperti mata dan gigi.",
                "Letakkan roti buaya di atas loyang yang sudah dialasi kertas roti. Diamkan selama 15-20 menit lagi untuk mengembang. Sebelum memanggang, Anda bisa menambahkan hiasan atau olesan permukaan jika diinginkan. Panggang dalam oven yang sudah dipanaskan pada suhu 180 derajat Celsius selama 20-25 menit atau hingga matang dan berwarna keemasan.",
                "Setelah matang, angkat roti buaya dari oven dan dinginkan sebelum disajikan.",
            ],
            shortDesc:"Roti yang beberntuk seperti buaya dan disajikan dalam acara pernikahan sebagai simbol kesetiaan dan kemapanan dalam budaya Betawi.",
            harga:"Rp15.000 - >Rp150.000"
        },
        {
            id: 18,
            nama: "Kue Pancong (Kelapa)",
            desc: "Kue Pancong adalah jajanan tradisional Betawi berbentuk cawan dengan pinggiran yang bergerigi, terbuat dari campuran tepung beras, kelapa parut, gula, santan, dan sedikit garam, kemudian dipanggang hingga matang dan berwarna kecokelatan. Rasanya gurih, manis, dan harum kelapa, sering dijadikan camilan favorit di Jakarta.",
            Kategori: ["Kue", "Tepung", "Santan", "Kelapa"],
            image: "../../../../public/assets/img/KuePancong.jpg",
            bahan: [
                "250 g tepung beras",
                "250 g kelapa setengah tua, kerok & parut memanjang",
                "700 ml santan sedang dari 1/2 butir kelapa",
                "5 sdm gula pasir",
                "1 sdt garam"
            ],
            cara: [
                "Dalam mangkuk besar, campurkan tepung beras, gula pasir, dan garam. Aduk rata.",
                "Tuangkan santan sedang ke dalam campuran tepung sedikit demi sedikit sambil terus diaduk hingga membentuk adonan yang halus dan kental.",
                "Setelah adonan tercampur rata, tambahkan kelapa parut. Aduk kembali hingga semua bahan tercampur dengan baik.",
                "Panaskan wajan khusus kue pancong atau wajan anti lengket di atas api sedang.",
                "Setelah wajan cukup panas, tuangkan adonan ke dalam cetakan kue pancong. Pastikan cetakan sudah diolesi sedikit minyak sebelumnya.",
                "Tutup wajan dan biarkan adonan mengeras dan matang di bagian bawah. Anda bisa mengecek dengan mencoba mengangkat bagian pinggir kue dengan menggunakan sendok kayu.",
                "Setelah bagian bawah kue matang, balik kue pancong dan biarkan bagian atasnya matang. Anda bisa membantu mematangkan bagian atas kue dengan menggunakan api kecil.",
                "Setelah kue matang dan berwarna kecokelatan di kedua sisi, angkat kue pancong dari wajan. Biarkan sedikit dingin sebelum disajikan.",
                "Kue pancong siap disajikan sebagai camilan atau hidangan penutup. Nikmati kue pancong hangat atau dingin sesuai selera Anda.",
            ],
            shortDesc:"Kue yang terdiri dari campuran tepung beras, kelapa parut, dan santan, dipanggang dalam cetakan khusus hingga berwarna kecokelatan dengan rasa gurih dan tekstur yang lembut.",
            harga:"Rp5.000 - Rp10.000"
        },
        {
            id: 19,
            nama: "Sayur Babanci",
            desc: "Sayur Babanci adalah hidangan khas Betawi yang terdiri dari campuran berbagai jenis sayuran seperti kacang panjang, terong, tahu, tempe, dan daun singkong yang dimasak dengan kuah santan kental yang diberi bumbu rempah seperti kemiri, lengkuas, dan kunyit. Rasanya gurih dan kaya akan rempah, sering disajikan sebagai lauk pendamping nasi dalam hidangan khas Betawi.",
            Kategori: ["Sayur", "Santan", "Kelapa"],
            image: "../../../../public/assets/img/",
            bahan: [
                "500 g daging sapi, rebus dengan +/- 1 liter air",
                "50 g kelapa parut, sangrai lalu haluskan",
                "200 ml air santan sedang (1 bungkus santan instan 65 ml + air)",
                "300 ml air kelapa",
                "[Rempah (sangrai, haluskan)]",
                "1/2 sdt lada putih",
                "1/2 sdt ketumbar",
                "1/2 sdt jintan",
                "1/2 sdt biji kedaung",
                "1/2 botor",
                "[Bumbu Halus]",
                "5 buah cabai merah keriting",
                "5 butir bawang merah",
                "3 siung bawang putih",
                "2 butir kemiri sangrai",
                "1 ruas jempol kunyit (5 g)",
                "1 ruas jempol jahe (5 g)",
                "1 ruas jempol bangle (5 g)",
                "[Bumbu Lainnya]",
                "1 batang sereh",
                "3 lembar daun salam",
                "Garam secukupnya (+/- 1,5 sdt)",
                "Gula merah secukupnya (+/- 1 sdm)",
                "[Pelengkap]",
                "Ketupat",
                "Bawang Goreng",
                "Emping"
            ],
            cara: [
                "Haluskan semua bahan bumbu halus menggunakan blender atau ulekan.",
                "Rebus daging sapi dengan +/- 1 liter air hingga empuk. Setelah empuk, angkat daging dan potong-potong sesuai selera.",
                "Tumis bumbu halus yang telah dihaluskan bersama dengan rempah yang sudah dihaluskan hingga harum dan matang.",
                "Setelah bumbu matang, tambahkan air kelapa dan air santan sedang. Aduk rata dan biarkan mendidih.",
                "Setelah mendidih, tambahkan potongan daging sapi yang sudah direbus ke dalam kuah. Biarkan mendidih kembali hingga daging empuk dan bumbu meresap.",
                "Setelah daging empuk, tambahkan kelapa parut yang sudah disangrai dan dihaluskan. Aduk rata dan biarkan mendidih sebentar lagi.",
                "Tambahkan garam secukupnya sesuai dengan selera dan gula merah secukupnya untuk memberikan rasa manis. Aduk rata dan cicipi rasanya, sesuaikan jika diperlukan.",
                "Sajikan sayur babanci bersama dengan pelengkap seperti ketupat, bawang goreng, dan emping.",
                "Sayur babanci siap disajikan sebagai hidangan utama. Nikmati hangat-hangat bersama dengan pelengkapnya.",
            ],
            shortDesc:"Hidangan langka yang terdiri dari campuran daging sapi dan sayuran yang dimasak dalam kuah santan beraroma rempah-rempah dan memberikan rasa gurih dan kaya",
            harga:"Rp10.000 - Rp25.000"
        },
        {
            id: 20,
            nama: "Putu Mayang",
            desc: "Putu Mayang adalah hidangan manis tradisional dari Indonesia, terutama dikenal di daerah Betawi. Terbuat dari tepung beras yang dibentuk seperti mie halus, kemudian direbus hingga matang. Setelah matang, putu mayang disajikan dengan kuah santan yang manis dan pandan. Hidangan ini memiliki tekstur lembut dan aromanya yang khas, sering disajikan sebagai makanan penutup atau camilan.",
            Kategori: ["Tepung", "Santan"],
            image: "../../../../public/assets/img/",
            bahan: [
                "150 g tepung beras",
                "50 g tepung tapioka",
                "1/2 sdt garam",
                "300 ml santan",
                "Pewarna hijau dan merah",
                "[Syrup Gula Merah]",
                "150 g gula merah",
                "50 g gula pasir",
                "500 ml santan encer",
                "1/2 sdt garam",
                "1 lembar daun pandan"
            ],
            cara:[
                "Dalam mangkuk besar, campurkan tepung beras, tepung tapioka, dan garam. Aduk rata.",
                "Tuangkan santan sedikit demi sedikit ke dalam campuran tepung sambil terus diaduk hingga membentuk adonan yang halus dan kental.",
                "Bagi adonan menjadi dua bagian. Tambahkan pewarna makanan hijau ke satu bagian dan merah ke bagian lainnya. Aduk hingga warna merata.",
                "Siapkan alat untuk membuat putu mayang. Gunakan cetakan putu mayang yang terbuat dari bahan plastik dengan lubang kecil. Panaskan panci pengukus dengan air. Letakkan cetakan di atasnya.",
                "Ambil satu warna adonan dan masukkan ke dalam cetakan putu mayang. Tekan-tekan hingga adonan keluar dari lubang cetakan dan membentuk seperti sotong kecil. Lakukan hal yang sama dengan adonan warna lainnya.",
                "Kukus putu mayang selama sekitar 10-15 menit atau hingga matang. Angkat dan biarkan dingin sejenak.",
                "Iris atau parut gula merah agar mudah larut. Siapkan juga daun pandan.",
                "Rebus gula merah, gula pasir, santan encer, garam, dan daun pandan dalam panci dengan api sedang hingga gula larut dan mendapatkan tekstur syrup yang kental. Aduk sesekali agar tidak gosong.",
                "Saring syrup gula merah untuk memisahkan daun pandan dan bahan lain yang tidak diinginkan.",
                "Letakkan putu mayang dalam piring saji atau mangkuk. Tuangkan syrup gula merah di atasnya secukupnya sesuai selera.",
                "Putu mayang siap disajikan sebagai hidangan penutup atau camilan. Nikmati selagi hangat atau dingin.",
            ],
            shortDesc:"Kue yang terbuat dari tepung beras yang dibentuk seperti mie dan disajikan dengan kuah santan manis yang terbuat dari gula merah, memberikan rasa manis dan tekstur kenyal yang khas.",
            harga:"Rp10.000 - Rp20.000"
        },
    ];

    module.exports = Food;